<?php
# This file was automatically generated by the MediaWiki 1.27.4
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings


$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);

$dotenv->Load(); 


# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Makerspace Leiden - Media wiki";
$wgMetaNamespace = "Makerspace_Leiden_-_Media_wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/mediawiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki.makerspaceleiden.nl";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "/msl.svg";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "wiki@makerspaceleiden.nl";
$wgPasswordSender = "wiki@makerspaceleiden.nl";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = $_ENV['WIKI_DB_HOST'];
$wgDBname = $_ENV['WIKI_DB_NAME']; 
$wgDBuser = $_ENV['WIKI_DB_USER']; 
$wgDBpassword = $_ENV['WIKI_DB_PASSWORD']; 

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
# $wgLanguageCode = "en";
$wgLanguageCode = "nl";

$wgSecretKey = $_ENV['WIKI_SECRET_KEY'];

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "a4e5df4546bedb0a";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/publicdomain/zero/1.0/";
$wgRightsText = "Creative Commons Zero (Public Domain)";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector-2022";
$wgDefaultUserOptions['vector-main-menu-pinned'] = 1;

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'Tabs' );


# End of automatically generated settings.
# Add more configuration options below.

# Debian specific generated settings
# Use system mimetypes
$wgMimeTypeFile = '/etc/mime.types';
# Load legacy extensions
if ( is_file( "/etc/mediawiki-extensions/extensions.php" ) ) {
	include "/etc/mediawiki-extensions/extensions.php";
}

# Add more configuration options below.
$wgSitename = "MakerSpace Leiden";
$wgMetaNamespace = "MakerSpace_Leiden";
$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'svg','pdf','scad','sch','brd', 'JPG', 'PNG', 'PDF', 'avi', 'mov', 'mpg', 'f3d', 'zip' , 'mch', 'obj', 'stp', 'step', 'object');

$wgDebugLogFile = "/var/log/mediawiki/debug-{$wgDBname}.log";
$wgDBerrorLog = '/var/log/mediawiki/dberror.log';

# Added this MLEB configuration:
wfLoadExtension( 'Babel' );

wfLoadExtension( 'cldr' );
wfLoadExtension( 'CleanChanges' );
$wgCCTrailerFilter = true;
$wgCCUserFilter = false;
$wgDefaultUserOptions['usenewrc'] = 1;

wfLoadExtension( 'LocalisationUpdate' );
$wgLocalisationUpdateDirectory = "$IP/cache";

$wgGroupPermissions['user']['translate'] = true;
$wgGroupPermissions['user']['translate-messagereview'] = true;
$wgGroupPermissions['user']['translate-groupreview'] = true;
$wgGroupPermissions['user']['translate-import'] = true;
$wgGroupPermissions['sysop']['pagetranslation'] = true;
$wgGroupPermissions['sysop']['translate-manage'] = true;
$wgTranslateDocumentationLanguageCode = 'qqq';
$wgExtraLanguageNames['qqq'] = 'Message documentation'; # No linguistic content. Used for documenting messages

wfLoadExtension( 'UniversalLanguageSelector' );
# end MLEB configuration:
#
# extra added to be able to set page language:
$wgPageLanguageUseDB = true;
$wgGroupPermissions['sysop']['pagelang'] = true;

# Set the maximum number of items shown per category to 500 (de-fault is 50)
#
$wgCategoryPagingLimit = 500;

# For fulco
#
$wgAllowUserCss=true;

wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'OpenIDConnect' );

$wgShowExceptionDetails = true; 

# Authentication
$wgGroupPermissions['*']['autocreateaccount'] = true;
$wgPluggableAuth_EnableLocalLogin = true;
$wgPluggableAuth_Config['Log in with Intranet'] = [
    'plugin' => 'OpenIDConnect',
    'data' => [
        'providerURL' => 'https://mijn.makerspaceleiden.nl/oauth2',
        'clientID' => $_ENV['WIKI_OAUTH_CLIENT_ID'], 
        'clientsecret' => $_ENV['WIKI_OAUTH_CLIENT_SECRET'],
	'scope' => ['openid', 'email'],
    'preferred_username' => 'name',
    ]
];
$wgOpenIDConnect_MigrateUsersByEmail = true;
$wgOpenIDConnect_UseRealNameAsUserName = true;


# Upload Wizard configuration
# This extension provides support for uploading multiple images
$wgEnableUploads = true;
$wgUseImageMagick = true;
wfLoadExtension( 'UploadWizard' );
